Update __init__.py
When using the create_table function and default Integer type, I get the error:
asyncpg.exceptions.DatatypeMismatchError: column "count_refer" is of type integer, but the default expression type is text
HINT: Rewrite the expression or convert its type.

columns = [
            {"name": "user_id", "type": BigInteger, "options": {"primary_key": True, "autoincrement": False}},
            {"name": "full_name", "type": String},
            {"name": "user_login", "type": String},
            {"name": "refer_id", "type": BigInteger},
            {"name": "count_refer", "type": Integer,"options": {"default": 0, "server_default": 0}},
            {"name": "date_reg", "type": TIMESTAMP},
        ]

CREATE TABLE users_reg (
	user_id BIGINT, 
	full_name VARCHAR, 
	user_login VARCHAR, 
	refer_id BIGINT, 
	count_refer INTEGER DEFAULT text('0'), 
	date_reg TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (user_id)
)
As I understand it, all default values ​​are converted to the String type...

            if default is not None:
                if isinstance(default, str):
                    server_default = func.text(default)
                else:
                    server_default = func.text(str(default))